### ISSUE TITLE
[TASK]: S3G4 Windows Virus Alert

### ISSUE THREAD

**Issue by EsraSaydan** [Workintech/nextgen-improvements#44]
### Sprint No

Sprint 3

### Gün No

Day 4

### Task No

Gün Projesi

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

1.Projeyi açtım 
2.Gün projesine kadar sorun yaşamadım
3.Gün Projesine geldiğimde bir satır kod yazdım ve bütün testlerden otomatik geçti. Bir önceki taskın testleri olduğunu farkettim 
...
![image](https://github.com/Workintech/nextgen-improvements/assets/161761900/e8cd4dfc-0854-4143-8cee-92becbf8c3e7)

**Comment by gokhanozdemir** [comment]
Esra selamlar, şüpheli algıladığının da ekranını paylaşır mısın? @EsraSaydan

**Comment by gokhanozdemir** [comment]
https://www.makeuseof.com/windows-chrome-virus-detected-error adresindeki adımları, ilerlerdikçe test ederek, yeniden bilgi verebilir misin?
