### ISSUE TITLE
[LESSON]: Sprint 06-03-2.2

### ISSUE THREAD

**Issue by NDKarabiberoglu** [Workintech/nextgen-improvements#5]
### Sprint No

Sprint 6

### Gün No

Day 3

### Hata bulunan sayfanın URL'si

https://nextgen.workintech.com.tr/lesson/6/3

### Task No

useEffect ile bir state değişimine bağlı bir resim getirmek

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

1.Video bütün halde devam ediyor 2.1 içinden aktıktan sonra 2.2 ye geçmiyor.
2.(2.2 açılmadığı için alıştırmaya da geçemiyor)
<img width="1435" alt="Ekran Resmi 2024-02-28 10 33 46" src="https://github.com/Workintech/nextgen-improvements/assets/100192397/1931e144-e6e5-4c80-99c7-53a3288c1f7b">

Öneri: Anlatım videosu 2'ye bölünebilir, Anlatım videosu tek kalabilir alıştırmalar birleştirilebilir.

**Comment by gokhanozdemir** [comment]
Teşekkürler, bunu içeri aktarıyorum.

**Comment by gokhanozdemir** [comment]
Teşekkürler, bunu içeri öneri olarak aktarıyorum.
