### ISSUE TITLE
[TASK]: 

### ISSUE THREAD

**Issue by ozenfurkan** [Workintech/nextgen-improvements#59]
### Sprint No

Sprint 1

### Gün No

Day 2

### Hata bulunan sayfanın URL'si

https://nextgen.workintech.com.tr/project/1/2/4

### Task No

4

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

1. Kod tamamen doğru olmasına rağmen tıpkı önceki görevlerdeki gibi ne zaman "return" ve "if else" kırmızı gözüküyorlar. Kod testten geçiyor ancak syntax hatası nedeniyle tamamlanmış gözükemiyor. 
2.SyntaxError: /home/projects/vitejs-vite-jxasdn/index.js: Unexpected token (16:6)
3.
...

**Comment by gokhanozdemir** [comment]
Ekran görüntüsü istemek için çok mu geç? @ozenfurkan
