### ISSUE TITLE
[LESSON]: Array ismi hatası

### ISSUE THREAD

**Issue by Mecasu** [Workintech/nextgen-improvements#6]
### Sprint No

Sprint 2

### Gün No

Day 3

### Hata bulunan sayfanın URL'si

https://nextgen.workintech.com.tr/lesson/2/3

### Task No

2. Map, sort ve reduce metodları -  Arrayin en büyük elemanını bulmak

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

1. Soruda bize "**Verilen sayı arrayinin en büyük elemanını bulan ve max isimli bir değişkene eşitleyen bir kod yazın.**" demesine karşılık sorunun içinde herhangi bir sayı array'i mevcut değil. Sayı array'inin ismini "**_sayilar_**" arrayinden farklı tanımlayınca hata veriyor.

**Comment by gokhanozdemir** [comment]
Teşekkürler, bunu içeri aktarıyorum.
