### ISSUE TITLE
[TASK]: Sayı Tahmin Oyunu

### ISSUE THREAD

**Issue by omerozyilmaz** [Workintech/nextgen-improvements#65]
### Sprint No

Sprint 1

### Gün No

Day 2

### Hata bulunan sayfanın URL'si

https://nextgen.workintech.com.tr/project/1/2/4

### Task No

Gun 2 task 4

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

1.Kodumda sıkıntı olmadığını görüyorum, özellikle sonuçlarla da karşılaştığımda eksik gözükmüyor ama %100 doğru alamıyorum.
![Ekran Resmi 2024-03-20 23 01 58](https://github.com/Workintech/nextgen-improvements/assets/125382539/6a2ba149-bb6a-46c3-adbe-d75814607034)

2.
3.
...

**Comment by gokhanozdemir** [comment]
Bu sistem çalışmasıyla ilgili olmayabilir. 24. satırda 
`'Kaybettin: (kullanıcı:' + tahmin + ',` 
değil 
`'Kaybettin: (kullanıcı: ' + tahmin + ',` olmalı
ek olarak sonucu console.log değil, return ile dönmelisin.
