### ISSUE TITLE
Java OOP Encapsulation[LESSON]: 

### ISSUE THREAD

**Issue by ilsusunal** [Workintech/nextgen-improvements#68]
### Sprint No

Sprint 13

### Gün No

Day 4

### Hata bulunan sayfanın URL'si

https://github.com/Workintech/FSWEB-S13D4-Maven

### Task No

Gün Projesi

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

1. nextgen'deki linke tıklayınca proje sayfası açılmıyor.
![image](https://github.com/Workintech/nextgen-improvements/assets/148697098/6783221c-9dcb-412c-b300-fbfc77f83a60)

**Comment by gokhanozdemir** [comment]
Şimdi çözülmüş olmalı.
