### ISSUE TITLE
[TASK]: WiT Gün Sonu Projesi Sprint 6 Gün 3 

### ISSUE THREAD

**Issue by NDKarabiberoglu** [Workintech/nextgen-improvements#7]
### Sprint No

Sprint 6

### Gün No

Day 3

### Hata bulunan sayfanın URL'si

https://nextgen.workintech.com.tr/project/6/3

### Task No

Gün Projesi

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

1.Sayfa yüklendikten sonra görev jsx leri açılınca test başarılı sonuçlanıyor.
2. Test adımları tamamlanmadan test geçilebiliyor.
3. Göreve baştan başla komutu verildiğinde test adımlarını yine geçiyor olarak gözlemlendi.
4. Sayfa refresh edip tekrar açılınca görev testleri kontrol ediliyor adımında kalıyor.
5. Proje dosyaları yüklenmiyor.
6. Bug 2 yeniden başla denilince düzeliyor / fakat kodları düzenlemeden tüm testler geçmiş gözüküyor.
7. App.jsx içindeki bütün kodları silmeme rağmen test başarılı oluyor.
![WiT Sprint 6 Gün 3 Gün Projesi Bug](https://github.com/Workintech/nextgen-improvements/assets/100192397/85635356-a0b8-4d60-b7c9-6b49401e6c00)
![WiT Sprint 6 Gün 3 Gün Projesi Bug1devam](https://github.com/Workintech/nextgen-improvements/assets/100192397/497b5849-5654-4ac0-b65c-e2b0b67aebb4)
![WiT Sprint 6 Gün 3 Gün Projesi Bug2](https://github.com/Workintech/nextgen-improvements/assets/100192397/dae7a883-75be-41d6-92b4-c2a01fe56f5d)

**Comment by gokhanozdemir** [comment]
Teşekkürler, bunu içeri aktarıyorum.
