### ISSUE TITLE
[TASK]: 

### ISSUE THREAD

**Issue by zehraBal** [Workintech/nextgen-improvements#77]
### Sprint No

Sprint 2

### Gün No

Day 3

### Hata bulunan sayfanın URL'si

https://nextgen.workintech.com.tr/project/2/3/2

### Task No

Görev 2

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

1.Görevde istenilenler tam anlamıyla yerine getirildiği halde beraberlik durumundaki değerleri yanlış kabul ediyor. 
2.
![console_ciktisi](https://github.com/Workintech/nextgen-improvements/assets/114819358/83bdc243-25d2-4d88-93a1-ac8c1ffd8e72)

3.
![wit_nextgen_hata](https://github.com/Workintech/nextgen-improvements/assets/114819358/6905ca53-b9de-4f97-85c2-30a5be60c70d)

...

**Comment by gokhanozdemir** [comment]
@zehraBal buna slack'ten devam edelim mi?
