### ISSUE TITLE
[TASK]: Boş proje testlerden geçiyor

### ISSUE THREAD

**Issue by aysenurcaglar** [Workintech/nextgen-improvements#9]
### Sprint No

Sprint 10

### Gün No

Day 4

### Hata bulunan sayfanın URL'si

https://nextgen.workintech.com.tr/project/10/4

### Task No

Task 1

### Karşılaştığınız hata nedir? Ne yapınca hata oluştu karşılaştınız?

Projede henüz hiçbir değişiklik yapmadım, sadece checkpoint'leri görmek için Kontrol Et tuşuna bastım ve tüm testlerden geçtiğimi söyledi.[
<img width="1080" alt="Ekran görüntüsü 2024-02-29 105042" src="https://github.com/Workintech/nextgen-improvements/assets/155725218/85a65c89-148b-4d31-97e7-7d66b3437a34">
]

**Comment by gokhanozdemir** [comment]
Teşekkürler içeri aktarıyorum
